# fix-generate-script.ps1
# Run this script from the root of the ViralForge project (same folder as package.json)
$ErrorActionPreference = "Stop"

$targetPath = Join-Path $PSScriptRoot "api\generate-script.js"

if (-not (Test-Path $targetPath)) {
    Write-Host "ERROR: file not found at $targetPath" -ForegroundColor Red
    Write-Host "Make sure fix-generate-script.ps1 is placed directly in the project root (where package.json is)." -ForegroundColor Red
    exit 1
}

$b64 = "ZXhwb3J0IGRlZmF1bHQgYXN5bmMgZnVuY3Rpb24gaGFuZGxlcihyZXEsIHJlcykgewogIGlmIChyZXEubWV0aG9kICE9PSAnUE9TVCcpIHsKICAgIHJldHVybiByZXMuc3RhdHVzKDQwNSkuanNvbih7IGVycm9yOiAnTWV0aG9kIG5vdCBhbGxvd2VkJyB9KTsKICB9CgogIGNvbnN0IHsgdG9waWMsIHBsYXRmb3JtLCBmb3JtYXQgfSA9IHJlcS5ib2R5OwoKICB0cnkgewogICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCgnaHR0cHM6Ly9vcGVucm91dGVyLmFpL2FwaS92MS9jaGF0L2NvbXBsZXRpb25zJywgewogICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgaGVhZGVyczogewogICAgICAgICdBdXRob3JpemF0aW9uJzogYEJlYXJlciAke3Byb2Nlc3MuZW52Lk9QRU5ST1VURVJfQVBJX0tFWX1gLAogICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicsCiAgICAgICAgJ0hUVFAtUmVmZXJlcic6ICdodHRwczovL3ZpcmFsLWZvcmdlLXRlbi52ZXJjZWwuYXBwJywKICAgICAgICAnWC1UaXRsZSc6ICdWaXJhbEZvcmdlJwogICAgICB9LAogICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7CiAgICAgICAgbW9kZWw6ICduZXgtYWdpL25leC1uMi41LW1pbmk6ZnJlZScsCiAgICAgICAgcmVhc29uaW5nX2VmZm9ydDogJ25vbmUnLAogICAgICAgIHJlc3BvbnNlX2Zvcm1hdDogeyB0eXBlOiAnanNvbl9vYmplY3QnIH0sCiAgICAgICAgbWVzc2FnZXM6IFsKICAgICAgICAgIHsKICAgICAgICAgICAgcm9sZTogJ3N5c3RlbScsCiAgICAgICAgICAgIGNvbnRlbnQ6IGBZb3UgYXJlIGEgdmlyYWwgY29udGVudCBleHBlcnQgZm9yICR7cGxhdGZvcm19LiBSZXNwb25kIHdpdGggT05MWSBhIHJhdyBKU09OIG9iamVjdCAobm8gbWFya2Rvd24gZmVuY2VzLCBubyBjb21tZW50YXJ5KSBtYXRjaGluZyBleGFjdGx5IHRoaXMgc2hhcGU6IHsiaG9vayI6IHN0cmluZywgImJvZHkiOiBzdHJpbmcsICJjdGEiOiBzdHJpbmcsICJ2aXJhbFNjb3JlIjogbnVtYmVyIGJldHdlZW4gMCBhbmQgMTAwfS5gCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICByb2xlOiAndXNlcicsCiAgICAgICAgICAgIGNvbnRlbnQ6IGBDcmVhdGUgYSB2aXJhbCAke2Zvcm1hdH0gc2NyaXB0IGFib3V0OiAiJHt0b3BpY30iLiBSZXR1cm4gb25seSB0aGUgSlNPTiBvYmplY3QuYAogICAgICAgICAgfQogICAgICAgIF0sCiAgICAgICAgdGVtcGVyYXR1cmU6IDAuOCwKICAgICAgICBtYXhfdG9rZW5zOiA1MDAKICAgICAgfSkKICAgIH0pOwoKICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7CgogICAgaWYgKCFyZXNwb25zZS5vayB8fCAhZGF0YS5jaG9pY2VzIHx8ICFkYXRhLmNob2ljZXNbMF0pIHsKICAgICAgY29uc29sZS5lcnJvcignT3BlblJvdXRlciBlcnJvciByZXNwb25zZTonLCBKU09OLnN0cmluZ2lmeShkYXRhKSk7CiAgICAgIHJldHVybiByZXMuc3RhdHVzKDUwMCkuanNvbih7CiAgICAgICAgZXJyb3I6ICdPcGVuUm91dGVyIEFQSSBlcnJvcicsCiAgICAgICAgc3RhdHVzOiByZXNwb25zZS5zdGF0dXMsCiAgICAgICAgZGV0YWlsczogZGF0YSwKICAgICAgfSk7CiAgICB9CgogICAgbGV0IGNvbnRlbnQgPSBkYXRhLmNob2ljZXNbMF0ubWVzc2FnZS5jb250ZW50IHx8ICcnOwogICAgLy8gU3RyaXAgbWFya2Rvd24gY29kZSBmZW5jZXMgaWYgdGhlIG1vZGVsIGFkZGVkIHRoZW0gZGVzcGl0ZSBpbnN0cnVjdGlvbnMuCiAgICBjb250ZW50ID0gY29udGVudC50cmltKCkucmVwbGFjZSgvXmBgYCg/Ompzb24pP1xzKi9pLCAnJykucmVwbGFjZSgvXHMqYGBgJC8sICcnKTsKCiAgICBsZXQgcGFyc2VkOwogICAgdHJ5IHsKICAgICAgcGFyc2VkID0gSlNPTi5wYXJzZShjb250ZW50KTsKICAgIH0gY2F0Y2ggKHBhcnNlRXJyKSB7CiAgICAgIGNvbnNvbGUuZXJyb3IoJ0NvdWxkIG5vdCBwYXJzZSBKU09OIGZyb20gbW9kZWwsIHJhdyBjb250ZW50OicsIGNvbnRlbnQpOwogICAgICByZXR1cm4gcmVzLnN0YXR1cygyMDApLmpzb24oewogICAgICAgIGhvb2s6ICcnLAogICAgICAgIGJvZHk6IGNvbnRlbnQgfHwgJ1RoZSBBSSByZXR1cm5lZCBhbiB1bmV4cGVjdGVkIHJlc3BvbnNlLiBQbGVhc2UgdHJ5IGFnYWluLicsCiAgICAgICAgY3RhOiAnJywKICAgICAgICB2aXJhbFNjb3JlOiA3NSwKICAgICAgICB3YXJuaW5nOiAnQUkgcmVzcG9uc2Ugd2FzIG5vdCB2YWxpZCBKU09OOyBzaG93aW5nIHJhdyBvdXRwdXQgaW4gQm9keS4nLAogICAgICB9KTsKICAgIH0KCiAgICBjb25zdCBob29rID0gU3RyaW5nKHBhcnNlZC5ob29rIHx8ICcnKS50cmltKCk7CiAgICBjb25zdCBib2R5ID0gU3RyaW5nKHBhcnNlZC5ib2R5IHx8ICcnKS50cmltKCk7CiAgICBjb25zdCBjdGEgPSBTdHJpbmcocGFyc2VkLmN0YSB8fCAnJykudHJpbSgpOwogICAgY29uc3QgdmlyYWxTY29yZSA9IE51bWJlci5pc0Zpbml0ZShwYXJzZWQudmlyYWxTY29yZSkgPyBNYXRoLnJvdW5kKHBhcnNlZC52aXJhbFNjb3JlKSA6IDc1OwoKICAgIHJlcy5zdGF0dXMoMjAwKS5qc29uKHsgaG9vaywgYm9keSwgY3RhLCB2aXJhbFNjb3JlIH0pOwoKICB9IGNhdGNoIChlcnJvcikgewogICAgY29uc29sZS5lcnJvcignZ2VuZXJhdGUtc2NyaXB0IGZhdGFsIGVycm9yOicsIGVycm9yKTsKICAgIHJlcy5zdGF0dXMoNTAwKS5qc29uKHsgZXJyb3I6ICdGYWlsZWQgdG8gZ2VuZXJhdGUnLCBkZXRhaWxzOiBTdHJpbmcoZXJyb3IpIH0pOwogIH0KfQo="
$bytes = [System.Convert]::FromBase64String($b64)
[System.IO.File]::WriteAllBytes($targetPath, $bytes)

Write-Host "OK: $targetPath updated." -ForegroundColor Green

Set-Location $PSScriptRoot
git add .
git commit -m "Switch to JSON-based structured output for reliable parsing"
git push

Write-Host "Committed and pushed. Vercel will redeploy in a minute." -ForegroundColor Green
