# fix-generate-script.ps1
# Run this script from the root of the ViralForge project (same folder as package.json)
$ErrorActionPreference = "Stop"

$targetPath = Join-Path $PSScriptRoot "api\generate-script.js"

if (-not (Test-Path $targetPath)) {
    Write-Host "ERROR: file not found at $targetPath" -ForegroundColor Red
    Write-Host "Make sure fix-generate-script.ps1 is placed directly in the project root (where package.json is)." -ForegroundColor Red
    exit 1
}

$b64 = "ZXhwb3J0IGRlZmF1bHQgYXN5bmMgZnVuY3Rpb24gaGFuZGxlcihyZXEsIHJlcykgewogIGlmIChyZXEubWV0aG9kICE9PSAnUE9TVCcpIHsKICAgIHJldHVybiByZXMuc3RhdHVzKDQwNSkuanNvbih7IGVycm9yOiAnTWV0aG9kIG5vdCBhbGxvd2VkJyB9KTsKICB9CgogIGNvbnN0IHsgdG9waWMsIHBsYXRmb3JtLCBmb3JtYXQgfSA9IHJlcS5ib2R5OwoKICB0cnkgewogICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCgnaHR0cHM6Ly9vcGVucm91dGVyLmFpL2FwaS92MS9jaGF0L2NvbXBsZXRpb25zJywgewogICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgaGVhZGVyczogewogICAgICAgICdBdXRob3JpemF0aW9uJzogYEJlYXJlciAke3Byb2Nlc3MuZW52Lk9QRU5ST1VURVJfQVBJX0tFWX1gLAogICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicsCiAgICAgICAgJ0hUVFAtUmVmZXJlcic6ICdodHRwczovL3ZpcmFsLWZvcmdlLXRlbi52ZXJjZWwuYXBwJywKICAgICAgICAnWC1UaXRsZSc6ICdWaXJhbEZvcmdlJwogICAgICB9LAogICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7CiAgICAgICAgbW9kZWw6ICdudmlkaWEvbmVtb3Ryb24tMy41LWxpZ2h0bmluZzpmcmVlJywKICAgICAgICBtZXNzYWdlczogWwogICAgICAgICAgewogICAgICAgICAgICByb2xlOiAnc3lzdGVtJywKICAgICAgICAgICAgY29udGVudDogYFlvdSBhcmUgYSB2aXJhbCBjb250ZW50IGV4cGVydCBmb3IgJHtwbGF0Zm9ybX0uYAogICAgICAgICAgfSwKICAgICAgICAgIHsKICAgICAgICAgICAgcm9sZTogJ3VzZXInLAogICAgICAgICAgICBjb250ZW50OiBgQ3JlYXRlIGEgdmlyYWwgJHtmb3JtYXR9IHNjcmlwdCBhYm91dDogIiR7dG9waWN9Ii4KRm9ybWF0OgpIT09LOiBbYXR0ZW50aW9uLWdyYWJiaW5nIG9wZW5pbmddCkJPRFk6IFttYWluIGNvbnRlbnRdCkNUQTogW2NhbGwgdG8gYWN0aW9uXQpWSVJBTF9TQ09SRTogWzAtMTAwXWAKICAgICAgICAgIH0KICAgICAgICBdLAogICAgICAgIHRlbXBlcmF0dXJlOiAwLjgsCiAgICAgICAgbWF4X3Rva2VuczogNTAwCiAgICAgIH0pCiAgICB9KTsKCiAgICBjb25zdCBkYXRhID0gYXdhaXQgcmVzcG9uc2UuanNvbigpOwoKICAgIGlmICghcmVzcG9uc2Uub2sgfHwgIWRhdGEuY2hvaWNlcyB8fCAhZGF0YS5jaG9pY2VzWzBdKSB7CiAgICAgIGNvbnNvbGUuZXJyb3IoJ09wZW5Sb3V0ZXIgZXJyb3IgcmVzcG9uc2U6JywgSlNPTi5zdHJpbmdpZnkoZGF0YSkpOwogICAgICByZXR1cm4gcmVzLnN0YXR1cyg1MDApLmpzb24oewogICAgICAgIGVycm9yOiAnT3BlblJvdXRlciBBUEkgZXJyb3InLAogICAgICAgIHN0YXR1czogcmVzcG9uc2Uuc3RhdHVzLAogICAgICAgIGRldGFpbHM6IGRhdGEsCiAgICAgIH0pOwogICAgfQoKICAgIGNvbnN0IGNvbnRlbnQgPSBkYXRhLmNob2ljZXNbMF0ubWVzc2FnZS5jb250ZW50OwoKICAgIGNvbnN0IGhvb2sgPSBjb250ZW50Lm1hdGNoKC9IT09LOlxzKiguKz8pKD89XG5cbkJPRFk6KS9zKT8uWzFdPy50cmltKCkgfHwgJyc7CiAgICBjb25zdCBib2R5ID0gY29udGVudC5tYXRjaCgvQk9EWTpccyooLis/KSg/PVxuXG5DVEE6KS9zKT8uWzFdPy50cmltKCkgfHwgJyc7CiAgICBjb25zdCBjdGEgPSBjb250ZW50Lm1hdGNoKC9DVEE6XHMqKC4rPykoPz1cblxuVklSQUxfU0NPUkU6KS9zKT8uWzFdPy50cmltKCkgfHwgJyc7CiAgICBjb25zdCBzY29yZU1hdGNoID0gY29udGVudC5tYXRjaCgvVklSQUxfU0NPUkU6XHMqKFxkKykvKTsKICAgIGNvbnN0IHZpcmFsU2NvcmUgPSBzY29yZU1hdGNoID8gcGFyc2VJbnQoc2NvcmVNYXRjaFsxXSkgOiA3NTsKCiAgICByZXMuc3RhdHVzKDIwMCkuanNvbih7IGhvb2ssIGJvZHksIGN0YSwgdmlyYWxTY29yZSB9KTsKCiAgfSBjYXRjaCAoZXJyb3IpIHsKICAgIGNvbnNvbGUuZXJyb3IoJ2dlbmVyYXRlLXNjcmlwdCBmYXRhbCBlcnJvcjonLCBlcnJvcik7CiAgICByZXMuc3RhdHVzKDUwMCkuanNvbih7IGVycm9yOiAnRmFpbGVkIHRvIGdlbmVyYXRlJywgZGV0YWlsczogU3RyaW5nKGVycm9yKSB9KTsKICB9Cn0K"
$bytes = [System.Convert]::FromBase64String($b64)
[System.IO.File]::WriteAllBytes($targetPath, $bytes)

Write-Host "OK: $targetPath updated." -ForegroundColor Green

Set-Location $PSScriptRoot
git add .
git commit -m "Switch to a currently-free OpenRouter model"
git push

Write-Host "Committed and pushed. Vercel will redeploy in a minute." -ForegroundColor Green
