# fix-generate-script.ps1
# Run this script from the root of the ViralForge project (same folder as package.json)
$ErrorActionPreference = "Stop"

$targetPath = Join-Path $PSScriptRoot "api\generate-script.js"

if (-not (Test-Path $targetPath)) {
    Write-Host "ERROR: file not found at $targetPath" -ForegroundColor Red
    Write-Host "Make sure fix-generate-script.ps1 is placed directly in the project root (where package.json is)." -ForegroundColor Red
    exit 1
}

$b64 = "ZXhwb3J0IGRlZmF1bHQgYXN5bmMgZnVuY3Rpb24gaGFuZGxlcihyZXEsIHJlcykgewogIGlmIChyZXEubWV0aG9kICE9PSAnUE9TVCcpIHsKICAgIHJldHVybiByZXMuc3RhdHVzKDQwNSkuanNvbih7IGVycm9yOiAnTWV0aG9kIG5vdCBhbGxvd2VkJyB9KTsKICB9CgogIGNvbnN0IHsgdG9waWMsIHBsYXRmb3JtLCBmb3JtYXQgfSA9IHJlcS5ib2R5OwoKICB0cnkgewogICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBmZXRjaCgnaHR0cHM6Ly9vcGVucm91dGVyLmFpL2FwaS92MS9jaGF0L2NvbXBsZXRpb25zJywgewogICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgaGVhZGVyczogewogICAgICAgICdBdXRob3JpemF0aW9uJzogYEJlYXJlciAke3Byb2Nlc3MuZW52Lk9QRU5ST1VURVJfQVBJX0tFWX1gLAogICAgICAgICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicsCiAgICAgICAgJ0hUVFAtUmVmZXJlcic6ICdodHRwczovL3ZpcmFsLWZvcmdlLXRlbi52ZXJjZWwuYXBwJywKICAgICAgICAnWC1UaXRsZSc6ICdWaXJhbEZvcmdlJwogICAgICB9LAogICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7CiAgICAgICAgbW9kZWw6ICdxd2VuL3F3ZW4tMi41LTdiLWluc3RydWN0OmZyZWUnLAogICAgICAgIG1lc3NhZ2VzOiBbCiAgICAgICAgICB7CiAgICAgICAgICAgIHJvbGU6ICdzeXN0ZW0nLAogICAgICAgICAgICBjb250ZW50OiBgWW91IGFyZSBhIHZpcmFsIGNvbnRlbnQgZXhwZXJ0IGZvciAke3BsYXRmb3JtfS5gCiAgICAgICAgICB9LAogICAgICAgICAgewogICAgICAgICAgICByb2xlOiAndXNlcicsCiAgICAgICAgICAgIGNvbnRlbnQ6IGBDcmVhdGUgYSB2aXJhbCAke2Zvcm1hdH0gc2NyaXB0IGFib3V0OiAiJHt0b3BpY30iLgpGb3JtYXQ6CkhPT0s6IFthdHRlbnRpb24tZ3JhYmJpbmcgb3BlbmluZ10KQk9EWTogW21haW4gY29udGVudF0KQ1RBOiBbY2FsbCB0byBhY3Rpb25dClZJUkFMX1NDT1JFOiBbMC0xMDBdYAogICAgICAgICAgfQogICAgICAgIF0sCiAgICAgICAgdGVtcGVyYXR1cmU6IDAuOCwKICAgICAgICBtYXhfdG9rZW5zOiA1MDAKICAgICAgfSkKICAgIH0pOwoKICAgIGNvbnN0IGRhdGEgPSBhd2FpdCByZXNwb25zZS5qc29uKCk7CgogICAgaWYgKCFyZXNwb25zZS5vayB8fCAhZGF0YS5jaG9pY2VzIHx8ICFkYXRhLmNob2ljZXNbMF0pIHsKICAgICAgY29uc29sZS5lcnJvcignT3BlblJvdXRlciBlcnJvciByZXNwb25zZTonLCBKU09OLnN0cmluZ2lmeShkYXRhKSk7CiAgICAgIHJldHVybiByZXMuc3RhdHVzKDUwMCkuanNvbih7CiAgICAgICAgZXJyb3I6ICdPcGVuUm91dGVyIEFQSSBlcnJvcicsCiAgICAgICAgc3RhdHVzOiByZXNwb25zZS5zdGF0dXMsCiAgICAgICAgZGV0YWlsczogZGF0YSwKICAgICAgfSk7CiAgICB9CgogICAgY29uc3QgY29udGVudCA9IGRhdGEuY2hvaWNlc1swXS5tZXNzYWdlLmNvbnRlbnQ7CgogICAgY29uc3QgaG9vayA9IGNvbnRlbnQubWF0Y2goL0hPT0s6XHMqKC4rPykoPz1cblxuQk9EWTopL3MpPy5bMV0/LnRyaW0oKSB8fCAnJzsKICAgIGNvbnN0IGJvZHkgPSBjb250ZW50Lm1hdGNoKC9CT0RZOlxzKiguKz8pKD89XG5cbkNUQTopL3MpPy5bMV0/LnRyaW0oKSB8fCAnJzsKICAgIGNvbnN0IGN0YSA9IGNvbnRlbnQubWF0Y2goL0NUQTpccyooLis/KSg/PVxuXG5WSVJBTF9TQ09SRTopL3MpPy5bMV0/LnRyaW0oKSB8fCAnJzsKICAgIGNvbnN0IHNjb3JlTWF0Y2ggPSBjb250ZW50Lm1hdGNoKC9WSVJBTF9TQ09SRTpccyooXGQrKS8pOwogICAgY29uc3QgdmlyYWxTY29yZSA9IHNjb3JlTWF0Y2ggPyBwYXJzZUludChzY29yZU1hdGNoWzFdKSA6IDc1OwoKICAgIHJlcy5zdGF0dXMoMjAwKS5qc29uKHsgaG9vaywgYm9keSwgY3RhLCB2aXJhbFNjb3JlIH0pOwoKICB9IGNhdGNoIChlcnJvcikgewogICAgY29uc29sZS5lcnJvcignZ2VuZXJhdGUtc2NyaXB0IGZhdGFsIGVycm9yOicsIGVycm9yKTsKICAgIHJlcy5zdGF0dXMoNTAwKS5qc29uKHsgZXJyb3I6ICdGYWlsZWQgdG8gZ2VuZXJhdGUnLCBkZXRhaWxzOiBTdHJpbmcoZXJyb3IpIH0pOwogIH0KfQo="
$bytes = [System.Convert]::FromBase64String($b64)
[System.IO.File]::WriteAllBytes($targetPath, $bytes)

Write-Host "OK: $targetPath updated." -ForegroundColor Green

Set-Location $PSScriptRoot
git add .
git commit -m "Add better error surfacing to generate-script API"
git push

Write-Host "Committed and pushed. Vercel will redeploy in a minute." -ForegroundColor Green
